### PR TITLE
Feature/zend.stdlib.hydrator.namingstrategy.mapnamingstrategy

### PR DESCRIPTION
**Pull request by nathanjosiah**

### CODE REVIEW

**Comment by nathanjosiah** [comment]
Related to #1396

**Comment by nathanjosiah** [comment]
I moved it back into the stdlib chapter

**Comment by weierophinney** [comment]
@nathanjosiah One comment: in the future, please do the pull request against the branch that you forked from. It's clear you forked from `develop`, but you issued the request against `master`; this takes a bit of time to unravel when merging.

**Comment by nathanjosiah** [comment]
@weierophinney Whoops, sorry about that!

**Pull request closed without merging**
