### PR TITLE
Add missing code so error is produced

### PR DESCRIPTION
**Pull request by edlongman**
If this function is omitted then a different error is seen. by adding this function it makes the runtime error show as expected by the tutorial

### CODE REVIEW

**Comment by manuakasam** [comment]
I'll check it this afternoon. Just looking over it briefly I'm not sure that's the case.

**Comment by froschdesign** [comment]
A complete paragraph is missing, which describes the error message for the missing controller action and the extension of the controller with the "list" action.

**Comment by manuakasam** [comment]
Precisely. Honestly I wonder where in the world that paragraph got lost :D
I'll get on it soon!

**Comment by edlongman** [comment]
I was just looking through is and thought, something is really wrong here
as that is the wrong error

**Comment by froschdesign** [comment]
@edlongman 
Can you create a new PR and close this one?

**Comment by manuakasam** [comment]
Ah damn, this is on me. Completely forgot about this one, will do it today,
sorry :)

Frank Brückner <notifications@github.com> schrieb am Do., 24. Sep. 2015 um
09:38 Uhr:

**Comment by froschdesign** [comment]
@manuakasam 
Nice! :+1:

**Comment by manuakasam** [comment]
OK, so I was just reading through the tutorial again getting my head around this.

The thing is: there's nothing wrong with it. We define a route that goes to `ListController` => `indexAction()`

We then create the controller without extending `AbstractActionController` which results in the error outlined in the documentation. After then extending the `AbstractActionController` we just get the error for the template. This is due to the fact that we rely on `indexAction()` rather than `listAction()` (or similar). The `indexAction()` is always provided per default from the `AbstractActionController`. Therefore the tutorial behaves correctly, I just tested this out.

@edlongman Can you describe what is happening on your end? My assumption is that you really just went with `listAction()` or something and therefore you see a different error. Am I correct with this assumption?

@froschdesign So in the end no error here after all. Though arguably relying on `indexAction()` may not have been the best course of action here. However the action-error-messages are covered at a later point within the tutorial when it comes to adding and editing the datasets.

**Comment by froschdesign** [comment]
@manuakasam 
> However the action-error-messages are covered at a later point within the tutorial when it comes to adding and editing the datasets.

Great! Thanks for your help.

**Comment by edlongman** [comment]
OK maybe I misunderstood this,  unfortunately I don't think I can replicate
what was happening but thank you for your help

**Comment by froschdesign** [comment]
@edlongman 
Please close this issue.

**Pull request closed without merging**
