### PR TITLE
Fixes #1267 - Remove all translated docs

### LINKED ISSUE #1267: [Proposal] Remove all translated docs
I know this proposal is radical, but all translated docs are outdated. ([See German as example](https://github.com/zendframework/zf2-documentation/tree/master/docs/languages/de/modules))
We still have plenty of work for the english version and if we remove all translated docs, we can focus on the problems that exist. ([Some examples](https://github.com/zendframework/zf2-documentation/issues/created_by/froschdesign))

### PR DESCRIPTION
**Pull request by froschdesign**
Fixes for `Makefile` are missing.

### CODE REVIEW

**Comment by GeeH** [comment]
Can I quickly ask who made the decision not to support translations please? Been out of the loop for a little while.

**Comment by Ocramius** [comment]
@GeeH see zendframework/zf2-documentation#1267

**Comment by GeeH** [comment]
Ping @weierophinney - can you fix the makefile please Matthew, then I will review this and merge it for 2.4 :sunglasses:

**Comment by froschdesign** [comment]
ping @weierophinney

**Comment by mwillbanks** [comment]
I could likely fix the make file..

**Comment by weierophinney** [comment]
Will fix it today as I review, @froschdesign.

**Comment by froschdesign** [comment]
@weierophinney 
Thanks!

**Pull request merged**
