### PR TITLE
 Added a note about the limit of 72 characters of bcrypt

### PR DESCRIPTION
**Pull request by ezimuel**
I rebased the develop branch and I re-apply my change. Fix for #1425

### CODE REVIEW

**Comment by weierophinney** [comment]
I'm going to merge this against master, as the new component it addresses is going into 2.3.4.

**Comment by weierophinney** [comment]
Saving this for 2.4.0; I've created an alternate with the same basic wording, but showing how to manually pre-hash for version 2.3.4.

**Comment by Ocramius** [comment]
@weierophinney was this actually merged? I see a merge commit and a conflicted PR now.

**Comment by weierophinney** [comment]
@Ocramius yes, it was merged. I forgot to close it, though.

**Pull request closed without merging**
